# Generated by Django 5.2.18 on 2026-10-08 18:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=10)),
                ('company_name', models.CharField(blank=True, help_text='For a contact person of a company.', max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('website', 'Website'), ('krisha', 'Krisha.kz'), ('referral', 'Referral'), ('call', 'Phone call'), ('social', 'Social media'), ('other', 'Other')], default='other', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Responsible manager.', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=4)),
                ('stage', models.CharField(choices=[('new', 'New lead'), ('contacted', 'Contacted'), ('viewing', 'Viewing'), ('negotiation', 'Negotiation'), ('contract', 'Contract'), ('won', 'Closed won'), ('lost', 'Lost')], db_index=True, default='new', max_length=12)),
                ('amount', models.PositiveBigIntegerField(default=0, help_text='Deal value in KZT.')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('created', 'Deal created'), ('stage', 'Stage changed'), ('owner', 'Owner changed'), ('task_done', 'Task completed')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Event details, e.g. {"from": "new", "to": "viewing"}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land')], default='apartment', max_length=12)),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=4)),
                ('district', models.CharField(choices=[('esil', 'Esil'), ('almaty', 'Almaty'), ('saryarka', 'Saryarka'), ('baikonyr', 'Baikonyr'), ('nura', 'Nura')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField(help_text='KZT. For rent: price per month.')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.property'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
            ],
            options={
                'ordering': ['is_done', 'due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'stage'], name='crm_deal_owner_i_4deb1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(condition=models.Q(('stage', 'contract')), fields=('property',), name='one_contract_per_property'),
        ),
    ]
